#!/usr/bin/env python3
"""Inject the Android-only "show in files" bridge into generated MainActivity.

Tauri's opener plugin intentionally does not implement revealItemInDir on
Android. The bridge opens Android's DocumentsUI/File Manager at the requested
shared-storage directory using ACTION_VIEW + vnd.android.document/directory,
with ACTION_OPEN_DOCUMENT_TREE as a fallback.

The Android project is generated by `tauri android init` on every CI run, so
this patch belongs in the build workflow rather than in src-tauri/gen.
"""
import glob
import re
import sys

BRIDGE = r'''

  override fun onWebViewCreate(webView: android.webkit.WebView) {
    webView.addJavascriptInterface(WritedFileManagerBridge(this), "WritedAndroidFileManager")
  }

  private class WritedFileManagerBridge(private val activity: android.app.Activity) {
    @android.webkit.JavascriptInterface
    fun reveal(path: String) {
      val target = java.io.File(path).let { if (it.isDirectory) it else it.parentFile ?: it }
      val root = "/storage/emulated/0/"
      if (!target.absolutePath.startsWith(root)) return
      val relative = target.absolutePath.removePrefix(root).trimStart('/')
      if (relative.isEmpty()) return

      val uri = android.net.Uri.parse(
        "content://com.android.externalstorage.documents/document/primary%3A" +
          android.net.Uri.encode(relative)
      )

      activity.runOnUiThread {
        val view = android.content.Intent(android.content.Intent.ACTION_VIEW).apply {
          setDataAndType(uri, "vnd.android.document/directory")
          addFlags(android.content.Intent.FLAG_GRANT_READ_URI_PERMISSION)
          putExtra("org.openintents.extra.ABSOLUTE_PATH", target.absolutePath)
        }
        try {
          if (view.resolveActivity(activity.packageManager) != null) {
            activity.startActivity(view)
            return@runOnUiThread
          }
        } catch (_: Exception) { }

        /* Fallback: Android's standard DocumentsUI can open at a supplied
           initial directory even when the OEM Files app doesn't implement
           ACTION_VIEW for directories. */
        try {
          val picker = android.content.Intent(android.content.Intent.ACTION_OPEN_DOCUMENT_TREE).apply {
            putExtra(android.provider.DocumentsContract.EXTRA_INITIAL_URI, uri)
          }
          activity.startActivity(picker)
        } catch (_: Exception) { }
      }
    }
  }
'''


def main():
    matches = glob.glob(
        "src-tauri/gen/android/app/src/main/java/**/MainActivity.kt", recursive=True
    )
    if not matches:
        print("android_file_manager: MainActivity.kt not found — skipping")
        return 0

    path = matches[0]
    with open(path, encoding="utf-8") as f:
        src = f.read()

    if "WritedAndroidFileManager" in src:
        print("android_file_manager: bridge already present — skipping")
        return 0

    m = re.search(r"class\s+MainActivity\s*:\s*TauriActivity\(\)\s*\{", src)
    if not m:
        print("android_file_manager: MainActivity does not extend TauriActivity() — skipping")
        return 0

    # Insert directly inside MainActivity. onWebViewCreate is a Tauri Android
    # lifecycle hook invoked when the native WebView has been created.
    patched = src[:m.end()] + BRIDGE + src[m.end():]
    with open(path, "w", encoding="utf-8") as f:
        f.write(patched)
    print("android_file_manager: patched " + path)
    return 0


if __name__ == "__main__":
    sys.exit(main())
